package com.yadhuChoudhary.MyRuns4

/**
 * Activity classifier using the Weka-generated decision tree
 * This classifier was trained on accelerometer data for Standing, Walking, and Running
 *
 * Generated with Weka 3.9.6 - J48 Decision Tree
 * Training data: features.arff from MyRuns Data Collector
 *
 * UPDATED: Wed Nov 19 19:53:29 PST 2025
 * This is YOUR personally trained classifier based on YOUR movement data
 */
class ActivityClassifier {

    companion object {
        // Activity type labels - MUST match the order your model was trained with
        val ACTIVITY_LABELS = arrayOf(
            "Standing",  // 0
            "Walking",   // 1
            "Running"    // 2
        )
    }

    /**
     * Classifies activity based on feature vector
     * @param features Feature vector extracted from accelerometer data (65 elements)
     * @return Activity type index (0=Standing, 1=Walking, 2=Running)
     */
    fun classify(features: DoubleArray): Int {
        if (features.size != 65) {
            return 0 // Default to Standing if invalid input
        }

        try {
            // Convert to Object array as expected by WekaClassifier
            val featureObjects = Array<Any?>(features.size) { i -> features[i] }

            // Call the Weka-generated classifier
            val prediction = WekaClassifier.classify(featureObjects)

            // Return the prediction as an integer
            return prediction.toInt().coerceIn(0, 2)
        } catch (e: Exception) {
            e.printStackTrace()
            return 0 // Default to Standing on error
        }
    }

    /**
     * Gets the activity label for an activity type index
     */
    fun getActivityLabel(activityType: Int): String {
        return if (activityType in ACTIVITY_LABELS.indices) {
            ACTIVITY_LABELS[activityType]
        } else {
            "Standing"
        }
    }

    /**
     * Checks if classifier is ready
     */
    fun isReady(): Boolean {
        return true // Always ready since we're using embedded code
    }
}

/**
 * Weka-generated classifier code - CONVERTED FROM JAVA TO KOTLIN
 * Generated with Weka 3.9.6 - J48 Decision Tree
 * Timestamp: Wed Nov 19 19:53:29 PST 2025
 *
 * This code was automatically generated by Weka from YOUR training data.
 * It represents a decision tree that classifies accelerometer features into activities.
 *
 * Classification outputs:
 * 0.0 = Standing
 * 1.0 = Walking
 * 2.0 = Running
 *
 * Input: Array of 65 features (64 FFT coefficients + 1 max magnitude)
 * Output: Double representing activity class (0.0, 1.0, or 2.0)
 *
 * Decision Tree Structure:
 * - Root node checks FFT coefficient 0 (overall motion intensity)
 * - If low (≤ 13.39) → Standing
 * - If high (> 13.39) → Check max magnitude (feature 64)
 *   - If very high (> 14.53) → Running
 *   - If moderate → Check FFT coefficient 4 and 7 to distinguish Walking/Running
 */
object WekaClassifier {

    /**
     * Main classification method
     * @param i Array of 65 features as Objects (Doubles)
     * @return Classification result (0.0, 1.0, or 2.0)
     */
    @Throws(Exception::class)
    fun classify(i: Array<Any?>): Double {
        var p = Double.NaN
        p = N3ccc6de90(i)
        return p
    }

    /**
     * First decision node - Root of the tree
     * Checks FFT coefficient 0 (first frequency component)
     *
     * This represents the overall intensity of motion.
     * Low values (≤ 13.39) indicate minimal movement = Standing
     * High values (> 13.39) indicate movement = need further classification
     */
    private fun N3ccc6de90(i: Array<Any?>): Double {
        var p = Double.NaN

        if (i[0] == null) {
            p = 0.0  // Default to Standing if null
        } else if ((i[0] as Double) <= 13.390311) {
            p = 0.0  // Standing - low first FFT coefficient
        } else if ((i[0] as Double) > 13.390311) {
            p = N4d66c0961(i)  // Movement detected - check further
        }

        return p
    }

    /**
     * Second decision node
     * Checks max magnitude (feature 64) - the peak acceleration
     *
     * This distinguishes between moderate movement (Walking)
     * and vigorous movement (Running)
     */
    private fun N4d66c0961(i: Array<Any?>): Double {
        var p = Double.NaN

        if (i[64] == null) {
            p = 1.0  // Default to Walking if null
        } else if ((i[64] as Double) <= 14.534508) {
            p = N51f13be92(i)  // Moderate magnitude - check more features
        } else if ((i[64] as Double) > 14.534508) {
            p = 2.0  // Running - high max magnitude indicates vigorous activity
        }

        return p
    }

    /**
     * Third decision node
     * Checks FFT coefficient 4 (frequency component 4)
     *
     * This helps distinguish between Walking and Running
     * when the max magnitude is moderate
     */
    private fun N51f13be92(i: Array<Any?>): Double {
        var p = Double.NaN

        if (i[4] == null) {
            p = 1.0  // Default to Walking if null
        } else if ((i[4] as Double) <= 14.034383) {
            p = N60645e843(i)  // Low frequency component 4 - final check
        } else if ((i[4] as Double) > 14.034383) {
            p = 1.0  // Walking - moderate frequency pattern
        }

        return p
    }

    /**
     * Final decision node (leaf)
     * Checks FFT coefficient 7 (frequency component 7)
     *
     * This is the final distinguishing feature between
     * Walking and Running for edge cases
     */
    private fun N60645e843(i: Array<Any?>): Double {
        var p = Double.NaN

        if (i[7] == null) {
            p = 1.0  // Default to Walking if null
        } else if ((i[7] as Double) <= 4.804712) {
            p = 1.0  // Walking - low frequency component 7
        } else if ((i[7] as Double) > 4.804712) {
            p = 2.0  // Running - high frequency component 7
        }

        return p
    }
}